version: '3.8'

services:
  emotion-recognition-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./code:/app/code
      - /dev/video0:/dev/video0  # Mount webcam device
    devices:
      - /dev/video0:/dev/video0  # Give access to webcam
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app/code
    restart: unless-stopped